version: '3.1'
services:
  mysql:
    image: 'mysql:5.7'
    restart: 'always'
    volumes:
      - ./cc_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=blog_db
      - MYSQL_USER=blog_user
      - MYSQL_PASSWORD=${BLOG_PASSWORD}
  blog:
    image: 'ghost:1-alpine'
    restart: 'always'
    expose:
      - '2368'
    environment:
      url: ${GHOST_URL}
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: blog_user
      database__connection__password: ${BLOG_PASSWORD}
      database__connection__database: blog_db
      mail__transport: SMTP
      mail__from: info@blog.cryptochains.in
      mail__options__service: Mailgun
      mail__options__auth__user: ${MAILGUN_USER}
      mail__options__auth__pass: ${MAILGUN_PASS}
    volumes:
      - ./cc_blog/content:/var/lib/ghost/content
    depends_on:
      - mysql
  website:
    image: 'bitnami/node:latest'
    restart: 'always'
    command: "sh -c 'npm install && npm start'"
    expose:
      - '3000'
    volumes:
      - ./cc_website:/app
    depends_on:
      - mysql
  portainer:
    image: 'portainer/portainer'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./cc_portainer:/data
    ports:
    - '9000:9000'
  bookstack:
    image: solidnerd/bookstack:0.19.0
    depends_on:
    - mysql
    environment:
    - DB_HOST=mysql:3306
    - DB_DATABASE=${BOOKSTACK_DB}
    - DB_USERNAME=${BOOKSTACK_USER}
    - DB_PASSWORD=${BOOKSTACK_PASS}
    volumes:
    - ./cc_bookstack/uploads:/var/www/bookstack/public/uploads
    - ./cc_bookstack/storage:/var/www/bookstack/public/storage
    expose:
    - '8080'
  webserver:
    image: 'cryptochains/nginx-amplify-pagespeed'
    restart: 'always'
    environment:
      - API_KEY=${AMPLIFY_API_KEY}
      - AMPLIFY_IMAGENAME=${AMPLIFY_IMAGENAME}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./cc_webserver/vhosts:/etc/nginx/conf.d/:ro
      - ./cc_webserver/certs:/etc/nginx/certs/:ro
      - ./cc_webserver/snippets:/etc/nginx/snippets/:ro
    links:
      - blog:blog
      - website:website
    depends_on:
      - blog
      - website
      - bookstack
